### ISSUE TITLE
go coverage import does not honour project base dir

### ISSUE THREAD

**Issue by psandhu79** [SonarSource/sonar-go-archived#218]
using the go plugin i am importing the cover.out file which looks like this 
9bumblebee-backend/adapters/pubsub_realization_notifier.go:41.151,43.16 2

using this  sonar.projectBaseDir=/usr/go-workspace/src/'  which contains  bumblebee-backend

however when importing i get the following warning

WARN: File '/root/bumblebee-backend/adapters/pubsub_realization_notifier.go' is not included in the project, ignoring coverage

i do not understand why this /root is being pre-pended  to the path

**Comment by eafzali** [comment]
kinda having the same problem. I'm running `sonar-scanner` inside the project directory, where the `coverage.out` is. 

The problem is that paths inside the `coverage.out` starts like `github.com/org/project/...` and I'm already in the `/home/go/src/github.com/org/project` directory, but I receive an error like: 
```
WARN: File '/home/go/src/github.com/org/project/github.com/org/project/pkg/file.go' is not included in the project, ignoring coverage
``` 
but it supposed to look for `/home/go/src/github.com/org/project/pkg/file.go`.

**Comment by alban-auzeill** [comment]
@psandhu79, @eafzali Could you provide the values of the GOPATH and GOROOT environment variables during go test and during sonar-scanner ?

The current assumptions about "go test" coverage report file are:
* path can be relative `github.com/org/project/pkg/file.go` and should be resolver as `$GOPATH/src/github.com/org/project/pkg/file.go`
* path can be absolute `_/root/pkg/file.go` and should be resolver as `/root/pkg/file.go`
* path is not relative to the project that is tested (that's why sonar.projectBaseDir is not used to resolve the relative path)

Do you know other cases of path resolution? Is it related to GOROOT?

**Comment by eafzali** [comment]
For me the problem was that `GOPATH` was not defined at all. I was using the default one which is `$HOME/go` https://golang.org/doc/code.html#GOPATH. so after explicitly setting the `GOPATH` it worked.

**Comment by eafzali** [comment]
@alban-auzeill so now our problem is that we are running sonar-scanner in another docker container other than the one we run our tests which produces `coverage.out`. so in the sonar-scanner docker we just mount the source code in `/src` and It works for all other types of projects we have just that it skips the coverage report because it can not resolve the paths correctly. 

Paths in `coverage.out` files are relative to `$GOPATH` but the project is not in the `$GOPATH` anymore when we run `sonar-scanner` it's just in `/src` so then it tries to resolve it as `/src/github.com/...`. do you think there is a way to handle this situation?

**Comment by psandhu79** [comment]
@eafzali i have the same problem. Using one container for testing and another for sonar scanner.

**Comment by saberduck** [comment]
@eafzali , @psandhu79 we've just released a new version [SonarGo 1.0](https://github.com/SonarSource/sonar-go/releases/download/1.0.0.1404/sonar-go-plugin-1.0.0.1404.jar) and we have a better way to match files from coverage report to the project files. Can you give it a try and see if it fixes your issue?

**Comment by tangyanhan** [comment]
Solved similar issue by setting GOPATH explicitly when running sonar-scanner. My GOPATH was $PWD:$PWD/vendor, so in the coverprofile, the go source files were relative.

**Comment by saberduck** [comment]
I believe original issue is fixed now. I am closing this one. In case you have some issue with coverage import please open a new issue.

**Comment by dantran** [comment]
we have multiple maven modules using mvngolang-wrapper plugin to build Go app at each module

dont think we can set GOPATH per module.  Any suggestion?

**Comment by alban-auzeill** [comment]
Hi @dantran,
It should be possible if you use "Multi-module Project Structure" described here: [Advanced SonarQube Scanner Usages](https://docs.sonarqube.org/display/SCAN/Advanced+SonarQube+Scanner+Usages).
Otherwise, sonar-go supports several directories in GOPATH separated with path separators ( ':' or on windows ';').

**Comment by dantran** [comment]
Thanks @alban-auzeill 
I would prefer the first option, but  dont think there is an option to setup  GOPATH per module.
